### ISSUE TITLE
getDirectoryPath() doesn't work on the web

### ISSUE THREAD

**Issue by feinstein** [miguelpruivo/flutter_file_picker#943] opened 2022-01-17 23:55 UTC
**Describe the bug**
getDirectoryPath() doesn't work on the web, I get an exception saying it was implemented 

**Platform**

- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Desktop

**Platform OS version**
Chrome and Edge on Windows 10

**Comment by philenius** [comment] 2022-01-19 17:22
@feinstein that’s not an issue. It's simply not supported on web, as pointed out in our [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/api#-getdirectorypath). Duplicate of #675. Feel free to provide an implementation if you know how to do implement it :wink: 

Sorry for any inconvenience.

**Closed by philenius** 2022-01-19 17:22 UTC
Labels: duplicate, new issue, web

**Comment by feinstein** [comment] 2022-01-19 17:57
I think this should be better documented on the README then. Most people won't open the wiki.

**Comment by miguelpruivo** [comment] 2022-01-19 20:02
@feinstein the readme points to the Wiki, which as per good practices, is the right place for the docs. 😀

**Comment by feinstein** [comment] 2022-01-19 23:34
Yes, but for simple packages, where people are only going to copy paste 1 function, it's natural to only read the README.

Also, the README should at least point out that not all features have full compatibility. It gives an impression that all features are present, when in fact they aren't.

**Comment by miguelpruivo** [comment] 2022-01-20 00:00
@feinstein sure, it’s important to note and be aware that some features are not implemented because some platforms doesn’t completely support it.

**Comment by feinstein** [comment] 2022-01-20 00:03
So I think the README should have a link for the compatibility chart, at the beginning of the README. Otherwise we keep reading and thinking everything is compatible, only to find way later that it isn't, and this makes us lose precious time.

It could be something as simple as "you can check platform compatibility per feature here"

**Comment by miguelpruivo** [comment] 2022-01-20 00:06
@feinstein yes, that sounds like a good idea, I might add a summarized table for the supported features in the README while keeping the details on the wiki.

**Comment by feinstein** [comment] 2022-01-20 00:07
Excellent.
