### ISSUE TITLE
Custom file type .tpl is unsupported and will be ignored

### ISSUE THREAD

**Issue by deacon78** [miguelpruivo/flutter_file_picker#332] opened 2020-07-23 08:41 UTC
Version : file_picker: ^1.13.0

Code to reproduce : `filePath = await FilePicker.getFilePath(type: FileType.custom,allowedExtensions: ['.tpl']);`

Error thrown : `Custom file type .tpl is unsupported and will be ignored`

Thank you

**Comment by miguelpruivo** [comment] 2020-07-23 09:21
This is working as intended. Not only file extensions in the world have MIME types to be supported. Thus, that exception is thrown on purpose to let you know.

In this case, your solution will be using `FileType.all` (or simply remove the file extension filter) and then validate the extensions on your end after picking by iterating through all paths and see if they respect that type. If not, you can present the user with an error and discard them to let him pick it again.

Closing as working as intended.
Thanks!

**Closed by miguelpruivo** 2020-07-23 09:21 UTC
Labels: new issue
