### ISSUE TITLE
iOS: The file couldn’t be opened because you don’t have permission to view it, While Picking images using File Picker 

### ISSUE THREAD

**Issue by DhavalRKansara** [miguelpruivo/flutter_file_picker#612] opened 2021-02-11 07:45 UTC
I am using file_picker to pick images from the photos in my project but when I select a photo using this package it gives me the below error:

**XCode 12.4 & iOS version 14.2**

```
2021-02-11 13:02:34.016715+0530 Runner[402:14919] 

***** Picker:<PHPickerViewController: 0x1080d7980> didFinishPicking:(
    "<PHPickerResult: 0x2828c0320>"
)
* -[FilePickerPlugin picker:didFinishPicking:] [Line 375]
2021-02-11 13:02:34.020813+0530 Runner[402:16374] [default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }
2021-02-11 13:03:35.089913+0530 Runner[402:16597] Error copying file type public.item. Error: Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x28269abe0 {Error Domain=NSCocoaErrorDomain Code=4101 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x28269aaf0 {Error Domain=PHAssetExportRequestErrorDomain Code=2 "(null)" UserInfo={NSUnderlyingError=0x28269b3c0 {Error Domain=CloudPhotoLibraryErrorDomain Code=81 "Failed to download CPLResourceTypeOriginal" UserInfo=0x283dc5040 (not displayed)}}}}}}
2021-02-11 13:03:35.090279+0530 Runner[402:16597] 

***** Could not load the picked given file: Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item, NSUnderlyingError=0x28269abe0 {Error Domain=NSCocoaErrorDomain Code=4101 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x28269aaf0 {Error Domain=PHAssetExportRequestErrorDomain Code=2 "(null)" UserInfo={NSUnderlyingError=0x28269b3c0 {Error Domain=CloudPhotoLibraryErrorDomain Code=81 "Failed to download CPLResourceTypeOriginal" UserInfo=0x283dc5040 (not displayed)}}}}}}
* -[FilePickerPlugin picker:didFinishPicking:]_block_invoke [Line 399]
2021-02-11 13:03:35.091735+0530 Runner[402:15116] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:239:5)
#1      takeImagesFromGallery (package:my_doses/src/utils/file_utils.dart:59:36)
<asynchronous suspension>
#2      loadImagesGallery (package:my_doses/src/utils/file_utils.dart:43:20)
<asynchronous suspension>
#3      _ContactPharmacyState._pickAttachment.<anonymous closure> (package:my_doses/src/contact_pharmacy/ui/contact_pharmacy.dart:605:15)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#14     _rootRunUnary (dart:async/zone.dart:1206:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _invoke1 (dart:ui/hooks.dart:267:10)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
2021-02-11 13:11:15.773760+0530 Runner[402:15119] [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
```

**Code:** 
```
  final image = await FilePicker.platform.pickFiles(type: FileType.image);
  if (image != null && image.files.first.path.isNotEmpty) {
    return File(image.files.first.path);
  } else {
    return null;
  }
```

**Flutter Doctor:** 
```
[✓] Flutter (Channel unknown, 1.20.0, on macOS 11.1 20C69, locale en-US)
    • Flutter version 1.20.0 at /Users/dhavalkansara/flutter 1.20/flutter
    • Framework revision 840c9205b3 (6 months ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhavalkansara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] Connected device (3 available)
    • dev’s iPhone (mobile) • 39756622f838a821cdde6e6780b16f32108d3fa0 • ios            • iOS 14.2
    • Web Server (web)      • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)          • chrome                                   • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
Process finished with exit code 0
```

**Comment by miguelpruivo** [comment] 2021-02-11 10:39
@DhavalRKansara did you ask the permissions to the info.plist file?

**Comment by DhavalRKansara** [comment] 2021-02-11 10:49
@miguelpruivo Yes I have added.

**Comment by DhavalRKansara** [comment] 2021-02-11 11:02
Also when 2nd time I call `FilePicker.platform.pickFiles(type: FileType.image)` it giving me below exception. 

![Screen Shot 2021-02-11 at 4 31 39 PM](https://user-images.githubusercontent.com/44993081/107628516-bd2a1000-6c86-11eb-8d9b-14cb454c9d10.png)

**Comment by miguelpruivo** [comment] 2021-02-12 12:09
@DhavalRKansara it looks like you trying to launch the picker multiple times. You can only open a new picker instance after closing the old one.

**Comment by miguelpruivo** [comment] 2021-02-19 10:39
Closing due to inactivity.

**Closed by miguelpruivo** 2021-02-19 10:39 UTC
Labels: new issue

**Comment by sproutlyCaleb** [comment] 2021-12-16 13:26
I am experiencing this issue too.

**Comment by SwissCheese5** [comment] 2021-12-24 17:17
I'm experiencing this on an iOS simulator running on an M1 macbook

```
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:353:35)
<asynchronous suspension>
#3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:89:33)
<asynchronous suspension>
```

**Comment by dancb10** [comment] 2022-01-04 10:24
I see this issue on physical iphone device

**Comment by riad-cot** [comment] 2022-03-10 17:55
Got the same issue with physical device and simulator (simulator can be tested by using IMG_0111)

**Comment by ArthurREGNARD** [comment] 2022-03-11 11:50
Got the same Issue ...

MacBook Pro M1, VM on iOS 15.2 - iPhone 13
On physical device to, iOS 15.3.1 - iPhone Xs Max

My code: 
```
FilePickerResult? result = await FilePicker.platform.pickFiles(
  type: FileType.image,
);
```

The error after image selection ...
```bash
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)
flutter: PlatformException(file_picker_error, Temporary file could not be created, Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.item" UserInfo={NSLocalizedDescription=Cannot load representation of type public.item}, null)
```

**Comment by banool** [comment] 2022-03-25 21:27
I'm seeing this issue with the video_player + flutter_cache_manager packages.

```
Unexpected error: PlatformException(VideoError, Failed to load video: The file couldn't be opened because you don't have permission to view it., null, null)
```

**Comment by PrathmeshPA** [comment] 2023-10-26 06:22
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, sharePositionOrigin: argument must be set, {{0, 0}, {0, 0}} must be non-zero and within coordinate space of source view: {{0, 0}, {1080, 810}}, null, null)
.
.
.
.
.
share_plus error Its working in simulator but gives this error on ipad16.7

**Comment by ubaidakmal** [comment] 2023-11-29 12:00
I have the same issue while using the video_player flutter package
video_player: ^2.6.0

and the error is

Error: -
flutter: PlatformException(VideoError, Failed to load video: The file couldn’t be opened because you don’t have permission to view it., null, null)

I gave all the permission and my flutter is also set perfectly and working perfectly

Solution:-
So I restarted my iPhone 8 device and then opened my app and everything worked fine no exceptions no bugs nothing else

UseCase: -
maybe it was caused by multiple requests to access files at a time
