### ISSUE TITLE
Please upgrade the web dependency to web: 1.0.0

### ISSUE THREAD

**Issue by najibkr** [miguelpruivo/flutter_file_picker#1574] opened 2024-08-09 05:03 UTC
**Describe the bug**
My app dependencies depends on other packages which use web: 1.0.0. I cannot override web to version 1.0.0, because my app doesn't compile. I would be really grateful if you could upgrade the web version to latest. 

**Platform**

- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?
Version 8.0.7

**How are you picking?**
```
Please, post the snippet here
```

**Details to reproduce the issue**
N/A

**Error Log**
N/A

**Screenshots and/or video**
N/A

**Flutter Version details**
N/A

**Additional context**
N/A

**Comment by jonmountjoy** [comment] 2024-08-09 14:03
Duplicate of https://github.com/miguelpruivo/flutter_file_picker/issues/1571

**Comment by navaronbracke** [comment] 2024-08-11 16:28
This is indeed a dupe of #1571

**Closed by navaronbracke** 2024-08-11 16:28 UTC
Labels: new issue
