### ISSUE TITLE
1.9.0: Can't build for iOS. Missing symbols in DKPhotoGallery

### ISSUE THREAD

**Issue by sgehrman** [miguelpruivo/flutter_file_picker#267] opened 2020-05-05 07:26 UTC
Undefined symbol: _OBJC_CLASS_$_FLAnimatedImageView

I switched back to 1.8.0+2 and it works.

Is there a work around?  I tried cleaning and rebuilding and nothing seemed to help.

I do have   use_frameworks! set

Showing Recent Messages
Ld /Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Products/Debug-journal-iphoneos/DKPhotoGallery/DKPhotoGallery.framework/DKPhotoGallery normal arm64 (in target 'DKPhotoGallery' from project 'Pods')
    cd /Users/steve/Documents/GitHub/therapist_training/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.4 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -L/Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Products/Debug-journal-iphoneos/DKPhotoGallery -F/Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Products/Debug-journal-iphoneos/DKPhotoGallery -F/Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Products/Debug-journal-iphoneos/FLAnimatedImage -F/Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Products/Debug-journal-iphoneos/SDWebImage -F/Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Products/Debug-journal-iphoneos/SDWebImageFLPlugin -filelist /Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Intermediates.noindex/Pods.build/Debug-journal-iphoneos/DKPhotoGallery.build/Objects-normal/arm64/DKPhotoGallery.LinkFileList -install_name @rpath/DKPhotoGallery.framework/DKPhotoGallery -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Intermediates.noindex/Pods.build/Debug-journal-iphoneos/DKPhotoGallery.build/Objects-normal/arm64/DKPhotoGallery_lto.o -Xlinker -export_dynamic -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Intermediates.noindex/Pods.build/Debug-journal-iphoneos/DKPhotoGallery.build/Objects-normal/arm64/DKPhotoGallery.swiftmodule -framework AVFoundation -framework AVKit -framework AssetsLibrary -framework Foundation -framework MobileCoreServices -framework Photos -framework UIKit -framework WebKit -framework AssetsLibrary -framework AVFoundation -framework AVKit -framework Foundation -framework MobileCoreServices -framework Photos -framework SDWebImage -framework SDWebImageFLPlugin -framework UIKit -framework WebKit -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Intermediates.noindex/Pods.build/Debug-journal-iphoneos/DKPhotoGallery.build/Objects-normal/arm64/DKPhotoGallery_dependency_info.dat -o /Users/steve/Library/Developer/Xcode/DerivedData/Runner-aqdnycdrzehvidcxnifzjwxjarnq/Build/Products/Debug-journal-iphoneos/DKPhotoGallery/DKPhotoGallery.framework/DKPhotoGallery

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FLAnimatedImageView", referenced from:
      type metadata for DKPhotoGallery.DKPhotoImageView in DKPhotoImageView.o
  "_OBJC_METACLASS_$_FLAnimatedImageView", referenced from:
      _OBJC_METACLASS_$__TtC14DKPhotoGallery16DKPhotoImageView in DKPhotoImageView.o
  "_OBJC_CLASS_$_FLAnimatedImage", referenced from:
      objc-class-ref in DKPhotoBaseImagePreviewVC.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by miguelpruivo** [comment] 2020-05-05 08:57
Go to your project’s iOS folder and run `pod install` command from there. Clean and build again.

If that doesn’t help, remove your Xcode derived data and try building again.

Typically that issue that you have on the logs is due to caching conflicts.

**Comment by sgehrman** [comment] 2020-05-05 20:32
tried all of that yesterday.  Nothing worked except reverting to 1.8.0

**Comment by miguelpruivo** [comment] 2020-05-05 21:59
@sgehrman 1.9.0 only introduced a new method. Nothing else, all dependencies kept the same. Run a `pod deintegrate`, remove your Pods folder and Podfile.lock and then do a `pod install` again.

Then, try building it with Xcode.

**Comment by miguelpruivo** [comment] 2020-05-05 23:09
@sgehrman I was able to reproduce your issue and got it fixed by just opening the iOS project with xcode then while pressing the option key go to Project > Clean build folder.

Build it again, it should be all good.

**Comment by dao-wkm** [comment] 2020-05-07 03:38
downgrade to 1.6.3+2 for resolve

`1.7.0 
Breaking change

Added support for multi-picks of videos and photos from Photos app on iOS through DKImagePicker — use any of the getMulti methods with FileType.image or FileType.video. From now on, you'll need to add use_frameworks! in your ios/Podfile.`

**Comment by miguelpruivo** [comment] 2020-05-07 09:09
@dao-wkm didnt quite get what you mean by that. 1.9.0 has a few updates that you might need, but since 1.7.0 you need to set `use_frameworks!` on your Podfile for it to work. Do you have it set?

**Comment by dao-wkm** [comment] 2020-05-07 09:13
yes, set `use_frameworks` for v1.9.0. If you don't want to set `use_frameworks` then use v1.6.3+2

**Comment by miguelpruivo** [comment] 2020-05-07 09:18
That’s correct @dao-wkm. But any particular reason why you would not? If you have any packages that don’t support building dynamically with `use_frameworks!` you can also add `use_modular_headers!` to allow Swift + Objective C to be mixed up.

**Comment by miguelpruivo** [comment] 2020-05-08 09:34
@dao-wkm were you able to use 1.9.0 with both `user_frameworks!` and `use_modular_headers!`? Just asking because if so, it might be good to add it on the docs.

Thanks.

**Closed by miguelpruivo** 2020-05-08 09:34 UTC
Labels: new issue

**Comment by dao-wkm** [comment] 2020-05-08 10:06
@miguelpruivo I confirm that use `file_picker: ^1.9.0+1` with `user_frameworks!` build iOS successfully

**Comment by sgehrman** [comment] 2020-05-09 09:49
works for me now too.  Not sure if option key Clean build folder did it, or something else.

**Comment by DanielApodaca** [comment] 2020-05-19 20:26
This is happening to me, i tried to clean but still not working. The thing is that im mixing plugins because i need to be able show a menu with option to choose sources (Like whatsapp, from camera (ImagePicker0.6.4), gallery(MultiImagePicker4.6.7) or documents(FilePicker1.9.0+1), im not sure how to do it all with a single plugin), i checked using only FilePicker and compiled fine, then tried adding ImagePicker but this error showed up:
[https://imgur.com/bEIxzap](url)
After that tried only file picker and multi image picker without success:
[https://imgur.com/hWMNaXP](url)

**Comment by miguelpruivo** [comment] 2020-05-19 20:41
@DanielApodaca you can use `file_picker` to pick multiple images or videos from gallery as well, you don’t actually need `multi_image_picker`.

Just use any of the `getMulti` methods with `FileType.image`.

**Comment by DanielApodaca** [comment] 2020-05-19 21:55
Thank you for the tip i thought that FileType.image only filtered the files, i deleted multi_image_picker but i'm still having issues with the regular image_picker

> https://imgur.com/bEIxzap

I will continue to try to find a solution, thank you for your time

**Comment by miguelpruivo** [comment] 2020-05-19 22:03
@DanielApodaca good thing is, you actually don't need `image_picker` as well if you plan to pick files only from gallery (images & videos). 

`FileType.image` will let you pick _all_ image files from gallery. If you need to pick videos and images, you can choose `FileType.media`.

**Comment by DanielApodaca** [comment] 2020-05-19 22:08
My boss wants to be able to choose the camera option, but i literally just fixed it, i tried so many times `flutter clean` but i found this [https://teratail.com/questions/249280](url) just needed to run `pod deintegrate` and `pod install` and it compiled properly

**Comment by miguelpruivo** [comment] 2020-05-19 22:18
@DanielApodaca yes, for camera you need `image_picker` (earlier versions of `file_picker` had camera as well, but I thought that it would be better to let users modulate their apps instead of having all in one plugin — however, I might consider adding it back).
