### ISSUE TITLE
Getter extension is not retuning correct extension when filename contain '.'

### ISSUE THREAD

**Issue by BlackStriker99** [miguelpruivo/flutter_file_picker#610] opened 2021-02-09 08:31 UTC
**Describe the bug**
Getter extension in PlatformFile is not fetching the correct extension when filename itself has a '.' in it.

My File Name:- "Roobaroo - Rang De Basanti(Jatt.fm).mp3"
Got Extension by calling getter extension:- ".fm"

**Platform**
- Android

**Platform OS version**
Android Q

**How are you picking?**
```
List<String> imageExtensions = [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "webp"
  ];

List<String> videoExtensions = [
    "mp4",
    "mov",
    "wmv",
    "flv",
    "avi",
    "webm",
    "mkv"
  ];

List<String> audioExtensions = ["m4a", "mp3", "ogg", "aac"];

 List<String> allowedExtensions =
        imageExtensions + videoExtensions + audioExtensions;

 FilePickerResult pickedMedia = await FilePicker.platform.pickFiles(
        allowMultiple: false,
        type: FileType.custom,
        allowedExtensions: allowedExtensions);

 String mediaType = getFileType(pickedMedia);

 String getFileType(FilePickerResult pickedMedia) {
    debugPrint("File path :- ${pickedMedia.files.single.path}");
    debugPrint("File name :- ${pickedMedia.files.single.name}");
    debugPrint("File extension :- ${pickedMedia.files.single.extension}");
    String extension = pickedMedia.files.single.extension;

    if (imageExtensions.contains(extension)) return "image";
    if (videoExtensions.contains(extension)) return "video";
    if (audioExtensions.contains(extension)) return "audio";
    return "";
  }

```

**Screenshots and/or video**
![Screenshot 2021-02-09 at 1 55 39 PM](https://user-images.githubusercontent.com/40071991/107335911-831e0a00-6ade-11eb-8383-a4b76a7a9ddf.png)

**Details to reproduce the issue**
Pick any file which has '.' in the file name and try to call getter .extension on that filePickerResult you will get the wrong extension

**Flutter Version details**
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/brijeshsakariya/development/flutter
    • Framework revision 7891006299 (9 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

**THANKS IN ADVANCE**

**Comment by miguelpruivo** [comment] 2021-02-09 10:46
Hi @BlackStriker99. There was a bug related with this that was fixed some versions ago. Could you please try updating to the latest plugin version and see if it’s still happening?

Thank you.

**Comment by BlackStriker99** [comment] 2021-02-09 12:44
> Hi @BlackStriker99. There was a bug related with this that was fixed some versions ago. Could you please try updating to the latest plugin version and see if it’s still happening?
> 
> Thank you.

Thanks for the reply @miguelpruivo appreciate your effort. 

I am using version

file_picker: ^2.1.6

![image](https://user-images.githubusercontent.com/40071991/107364552-9b535080-6b01-11eb-9385-4fc27256ce05.png)

I tried to run again and still getting the same issue with the different files also.
NEW FILENAME:- Humsafar SongsMp3.Co.mp3

**THANKS IN ADVANCE**

**Comment by miguelpruivo** [comment] 2021-02-09 13:15
@BlackStriker99 looks like everything is as intended. For some reason, the file name is being handled in a wrong way on the native side (which I can't control, that's where the OS gives me the files you've just picked) and then, since the name is wrong, hence is the extension.

Could you please try with a different device?

**Comment by BlackStriker99** [comment] 2021-02-09 14:17
Hello, @miguelpruivo **THANKS** for your support.

I have tried in the emulator as well as in two different devices still giving me the same issue.

About the name of the file, we can never know which type of filename the user will select. 
So I think it would be good if we can handle this type of situation.

So basically in my code I just want to know which type of file user has selected is it audio, is it video or it is an image.

It would be also good if we can have one getter like which kind of file user has selected.

 If there is any update regarding this extension issue then please let me know.
 
 **EXTRA**
 
 If you know any better way to get a type of the selected file without using an extension then please let me know.

**THANKS IN ADVANCE**

**Comment by miguelpruivo** [comment] 2021-02-09 14:37
@BlackStriker99 I believe that you can assume the type if you are restricting it already using any of the available `FileType` types. If the user selects using a `FileType.any` any guess would be based on the file extension. I believe there's not really a big way around this, I'm sorry.

**Comment by BlackStriker99** [comment] 2021-02-10 08:08
OK, **THANKS FOR YOUR HELP** @miguelpruivo 

if you solve this issue in the future to get the right extension for this kind of file name then please let me know about it.

**Comment by miguelpruivo** [comment] 2021-02-10 10:26
No problem @BlackStriker99. I’m sorry for any inconvenience.

**Comment by miguelpruivo** [comment] 2021-03-03 21:57
Closing since I'm afraid there isn't much to do here.

**Closed by miguelpruivo** 2021-03-03 21:57 UTC
Labels: new issue
