### ISSUE TITLE
No display of the app directory

### ISSUE THREAD

**Issue by Mike-3** [miguelpruivo/flutter_file_picker#703] opened 2021-04-30 07:21 UTC
**Platform**
- Android

Why do I only see the media folder under the Android directory. I even have the MANAGE_EXTERNAL_STORAGE permission. Still, I don't see any other folders. I was able to display the folder structure in another app that had the same rights. And that wasn't a system app. I would need access to the app folder, because files from the app are saved there that I want to read again when necessary. Can someone give me a tip on how I can do that.

**Comment by miguelpruivo** [comment] 2021-05-02 14:35
Please try with version 3.0.0 instead of 3.0.1 and let me know if it’s working for you.

Make sure you use `file_picker: 3.0.0` Without the `^` so it doesn’t fetch the 3.0.1.

**Comment by Mike-3** [comment] 2021-05-02 19:03
Thank you for your answer.
I tested your proposal. Unfortunately nothing has changed. 

![grafik](https://user-images.githubusercontent.com/70719484/116824261-8b3f9000-ab89-11eb-948e-4fd91eca9b16.png)

**Comment by miguelpruivo** [comment] 2021-05-09 15:28
How are you picking?

**Comment by miguelpruivo** [comment] 2021-05-12 11:48
If you tap here what happens?
<img width="141" alt="Captura de ecrã 2021-05-12, às 12 48 35" src="https://user-images.githubusercontent.com/27860743/117970261-5f0dd700-b320-11eb-8ac4-f7747f671365.png">

**Comment by Mike-3** [comment] 2021-05-12 13:10
![grafik](https://user-images.githubusercontent.com/70719484/117980277-18c27300-b334-11eb-84d0-21fc158bae4b.png)

I think, this is ok.

**Comment by miguelpruivo** [comment] 2021-05-14 13:42
Ok, that's how it should work. There isn't any issue. You can navigate to your folders from there or tap on the cake icon on the app bar to pick different locations.

Closing as this is working as intended.

**Closed by miguelpruivo** 2021-05-14 13:42 UTC
Labels: awaiting response
