### ISSUE TITLE
App Exits after picking a file

### ISSUE THREAD

**Issue by TesfahunK** [miguelpruivo/flutter_file_picker#210] opened 2020-03-15 08:42 UTC
i recently upgraded to v 1.5 , tried picking a file(multiple), then app exits without no error message or exception , i thought it was related to multiple files ,but its the same for single file, the previous version(1.4.3+2 ) works just fine ,

**Comment by Hopheylalal** [comment] 2020-03-15 08:46
Same problem!

**Comment by Marcosmaliki** [comment] 2020-03-15 09:07
same problem but with an deprecation error message

**Comment by SeifKaroui** [comment] 2020-03-15 09:57
Same problem here.
Even when picking just one file.

**Comment by miguelpruivo** [comment] 2020-03-15 10:28
Could you please check your adb logcat and then post the logs?

I need further details to help me check what might have cause it.

Thank you!

**Comment by miguelpruivo** [comment] 2020-03-15 11:10
Btw, @TesfahunK @Marcosmaliki @SeifKaroui did you update the `FileType` with camelCase after updating? You shouldn't be able to build anyway.

I've been strongly trying to replicate this on emulator/device but it is working as intended, both on release and debug builds.

**Comment by miguelpruivo** [comment] 2020-03-15 12:21
Ok, further update: I found the issue and I'm already working on it.

You should get some logs like this anyway:
```
E/AndroidRuntime(32542): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(32542): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate.finishWithSuccess(FilePickerDelegate.java:186)
E/AndroidRuntime(32542): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate.access$100(FilePickerDelegate.java:20)
E/AndroidRuntime(32542): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:98)
```

**Comment by RashminDungrani** [comment] 2020-03-15 13:26
same problem !
and not working flutter clean or full restart ...

**Comment by miguelpruivo** [comment] 2020-03-15 13:59
Ok, found the issue and it's actually directly related to the Flutter engine and not the plugin itself where it calls `onActivityResult()` twice when it shouldn't, as mentioned [here](https://github.com/flutter/flutter/issues/49365) and [here](https://github.com/flutter/flutter/issues/49105).

This fix is landed on Flutter for versions above 1.14.6, like pointed [here](https://github.com/flutter/flutter/issues/49365#issuecomment-583544824), so that means that if you are running on `master`, `beta` or `dev`, you won't have this issue whereas `stable` will do, for now.

Nevertheless, today I'm releasing 1.6.0 with web support and I'll add a temporary workaround for those on stable.

**Comment by miguelpruivo** [comment] 2020-03-15 14:26
Added a temporary workaround for it and landed on pub.dev for [1.5.0+1](https://pub.dev/packages/file_picker#1501).

Please, run a `flutter clean` and let me know if it worked for you.

Thank you all.

**Comment by SeifKaroui** [comment] 2020-03-15 23:05
> Added a temporary workaround for it and landed on pub.dev for [1.5.0+1](https://pub.dev/packages/file_picker#1501).
> 
> Please, run a `flutter clean` and let me know if it worked for you.
> 
> Thank you all.

Thanks for your efforts.
It's working now 😃

**Closed** 2020-03-16 00:07 UTC
Labels: awaiting response, bug, wip

**Comment by Marcosmaliki** [comment] 2020-03-16 07:45
Thank you. All working perfectly. We should buy you coffee ☕

**Comment by arsalalgorepublic** [comment] 2021-11-05 07:58
same problem
