### ISSUE TITLE
Having quotes "" in file name leads to invalid file path

### ISSUE THREAD

**Issue by travisjayday** [miguelpruivo/flutter_file_picker#172] opened 2019-11-11 19:06 UTC
Hi, I'm trying to select the file with name ```("###PDF n asdfm eesf")$".pdf``` but ```var path = await FilePicker.getFilePath(type: FileType.ANY);``` returns only ```(``` as the filename. E.g. everything after the first quotation mark gets truncated. This is not good obviously. Looks like file paths aren't sanitized correctly?

**Comment by miguelpruivo** [comment] 2019-11-11 19:08
Hi @travisjayday this shouldn't happen. In which platform is this issue on?

**Comment by travisjayday** [comment] 2019-11-11 19:10
Tested on Pixel 2 API 28 virtual device. Here is the relevant code: 

`void _pickFile() async {
    var path = await FilePicker.getFilePath(type: FileType.ANY);
    print("Selected file: " + path.toString());`

**Comment by miguelpruivo** [comment] 2019-11-11 19:10
Ok. I'll take a look ASAP @travisjayday. Thank you.

**Comment by miguelpruivo** [comment] 2019-11-18 12:39
Hi @travisjayday, this looks similar to #166 where you both are using [reserved Android character](https://stackoverflow.com/questions/2679699/what-characters-allowed-in-file-names-on-android) names. This make it even harder to debug because I can't have files with that name as it most of the times, the system will automatically replace with `_`. You can try it yourself by going to a File Explorer and try to rename a file to include `"` or any other invalid character, and you'll see that it will be replaced with an `_`.

Anyhow, if you find a way to force it to have that name or provide me with a url for such, I may give it a try and see what I can do. But bottom line is that there shouldn't be files with invalid file names.

**Comment by travisjayday** [comment] 2019-11-18 17:25
Hi @miguelpruivo, reserved Android characters or not, I think it is certainly possible that users may have files with hose characters. The Pixel emulator when downloading PDF files from chrome even shows an alert Dialog in which the user can specify a file name (with however many special characters) for the downloaded PDF. I also tested this on my phone (Xiaomi mi mix 3) and the Google Files file manager app allows for renaming files with special characters + another file manager I use also allows for renaming with those special characters in the OP.

**Comment by miguelpruivo** [comment] 2019-11-18 23:37
@travisjayday I understand, but you will have to provide me with full steps to reproduce your issue otherwise I can't find a way to help you as I don't really can (and believe me, I've tried even of different SDK emulators, with API 28 and 29) but the files always get renamed to `_` when I try to add an invalid character like `"` in the name, even when downloading from Chrome.

Tell me the emulator model and API version and how are you doing it. I've even downloaded some file explorer apps in order to make it possible to rename, but some of them don't even allow me _at all_ to introduce invalid characters to the name. It's like a no-no for me.

Nevertheless, I still would like to help you.

**Comment by miguelpruivo** [comment] 2020-01-21 00:07
I'm closing this since no further info was been given in the meantime. Feel free to re-open it if you have more details.

Thank you.

**Closed by miguelpruivo** 2020-01-21 00:07 UTC
Labels: bug, wip
