### ISSUE TITLE
Latest version have a confict with another library

### ISSUE THREAD

**Issue by pqtrong17** [miguelpruivo/flutter_file_picker#454] opened 2020-10-22 04:18 UTC
I get a error with version `file_picker 2.0.9+1`
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\WORKING\diday\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_country_picker...
Running Gradle task 'assembleAarRelease'...


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'flutter_country_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Exception: The plugin flutter_country_picker could not be built due to the issue above.
```
but no for `file_picker: ^1.13.3`. My app works perfectly with this release.

**Comment by pqtrong17** [comment] 2020-10-22 05:04
flutter doctor -v
```
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.22.2 at C:\Users\pqtrong17\AppData\Local\Android\flutter
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pqtrong17\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • SM N950U (mobile) • ce08171854d3a940017e • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

**Comment by miguelpruivo** [comment] 2020-10-22 09:11
@pqtrong17 the issue is described in the changelog and in the troubleshooting area [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#android).

You need to upgrade your gradle version to support the latest features.

**Comment by miguelpruivo** [comment] 2020-10-22 09:15
Closing as dup of #455.

**Closed by miguelpruivo** 2020-10-22 09:15 UTC
Labels: new issue
