### ISSUE TITLE
Can you change the way it runs on macOS?

### ISSUE THREAD

**Issue by rigroch** [miguelpruivo/flutter_file_picker#1145] opened 2022-10-07 02:11 UTC
In summary, use Channel like iOS.

Please use beginSheetModal instead of runModal. (runModal works the same as the way uses osascript you were written.)

```
guard let keywindow = NSApplication.shared.keyWindow else {
    result(nil)
    return
}

NSOpenPanel().beginSheetModal(for: keywindow) { response in
    
}
```

It appears more beautiful appearance, and to solve the [issue](https://github.com/miguelpruivo/flutter_file_picker/issues/1059).

**Comment by stuartmorgan** [comment] 2022-11-11 11:58
> runModal works the same as the way uses osascript you were written.

This isn't actually correct; an in-process `runModal` call would already be vastly better than `osascript`. The latter is not intended for use in GUI applications, and shows the dialog in *a completely separate process*, which creates significant issues around focus and window management.

**Comment by Hixie** [comment] 2024-02-13 22:46
I imagine this would also fix https://github.com/miguelpruivo/flutter_file_picker/issues/1445

**Comment by navaronbracke** [comment] 2024-04-18 20:03
Closing this issue as a duplicate of https://github.com/miguelpruivo/flutter_file_picker/issues/1492 since that issue has a better explanation of what needs to change.

**Closed by navaronbracke** 2024-04-18 20:03 UTC
Labels: suggestion, feature-candidate, desktop
