### ISSUE TITLE
IllegalStateException in Android

### ISSUE THREAD

**Issue by davidmartos96** [miguelpruivo/flutter_file_picker#159] opened 2019-10-15 13:23 UTC
**Describe the bug**
A crash was registered in Google Play from one of the users of my app. I'm not able to reproduce it.

**File picker version: 1.4.2**

**Issue details**
Device LGE LBello (luv80ss), Android 4.4

**Error Log**
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:3387)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:3430)
  at android.app.ActivityThread.access$1300 (ActivityThread.java:142)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1251)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5118)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:789)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:605)
  at dalvik.system.NativeStart.main (Native Method)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:151)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:225)
  at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult (FilePickerPlugin.java:108)
  at io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:204)
  at io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:132)
  at io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:142)
  at android.app.Activity.dispatchActivityResult (Activity.java:5467)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:3383)
```

**Flutter Version details**
Flutter v1.9.1+hotfix.4

**Comment by miguelpruivo** [comment] 2019-10-27 12:08
I'm not able to reproduce this as well @davidmartos96 and I've only found one similar issue while researching for this that seems to happen only when on release with app bundle built apps. However, the device can also have a custom rom that could affect this or/and be one time only exception. Because of that, I'm going to close this until.

Just let me know if this this is still an issue for that specific user or if it happened only once, if so, feel free to reopen this, preferably with more details. 

Thank you!

**Closed by miguelpruivo** 2019-10-27 12:08 UTC
Labels: new issue
