### ISSUE TITLE
compile error on 8.1.5, FilePickerPlugin.java:257: error: cannot find symbol

### ISSUE THREAD

**Issue by yoer** [miguelpruivo/flutter_file_picker#1651] opened 2024-12-16 11:18 UTC
/Users/yoer/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:257: error: cannot find symbol
        if (registrar != null) {
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
/Users/yoer/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:260: error: cannot find symbol
            registrar.addActivityResultListener(this.delegate);
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':file_picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by uzairmughal3397** [comment] 2024-12-16 14:23
Having same issue.

**Comment by YesThatGy** [comment] 2024-12-16 16:30
Facing same issue. Also found reference to SO: https://stackoverflow.com/questions/79284332/flutter-execution-failed-for-task-file-pickercompiledebugjavawithjavac/79285378#79285378

Upgrading to latest version did not improve things, even with flutter clean && flutter pub get.

**Comment by DevMoAbdeen** [comment] 2024-12-16 16:36
Updated to version 8.1.6 of the file_picker package.

**Comment by MrCsabaToth** [comment] 2024-12-16 20:22
Duplicate of #1643

**Comment by yoer** [comment] 2024-12-17 02:13
> Duplicate of #1643 ?

yes, It seems that many people have encountered this problem

**Closed** 2024-12-17 02:14 UTC
Labels: new issue
