### ISSUE TITLE
Dialog is opened two times and requires android.permission.ACCESS_ALL_DOWNLOADS

### ISSUE THREAD

**Issue by kleyos** [miguelpruivo/flutter_file_picker#127] opened 2019-08-22 07:34 UTC
When I try to pick the document I can see in console the messagesI
```
/FilePicker(10657): [SingleFilePick] File URI:content://com.android.providers.downloads.documents/document/4132
E/FilePickerUtils(10657): Getting for API 19 or abovecontent://com.android.providers.downloads.documents/document/4132
E/FilePickerUtils(10657): Document URI
E/FilePickerUtils(10657): Downloads External Document URI
E/FilePickerUtils(10657): Something went wrong while retrieving document path: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/4132
E/FilePickerUtils(10657): Something went wrong while retrieving document path: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/4132 from pid=10657, uid=10297 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
I/FilePickerUtils(10657): Caching file from remote/external URI
I/FilePickerUtils(10657): File loaded and cached at:/data/user/0/com.lits.switchin/cache/file.pdf
I/FilePicker(10657): Absolute file path:/data/user/0/com.lits.switchin/cache/file.pdf

```
I've already granted all permissions
`    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_ALL_DOWNLOADS"/>
`
And I can pick the file from the second time only

**Comment by miguelpruivo** [comment] 2019-08-22 08:03
Hi. This is a known issue that I’m looking into. 

Interesting that it works at the second time for you. What if you remove the access all downloads permission, does it work? Can you post your flutter doctor for that issue? I need more details of the device’s Android version and model.

Thank you.

**Comment by kleyos** [comment] 2019-08-22 08:29
> Hi. This is a known issue that I’m looking into.
> 
> Interesting that it works at the second time for you. What if you remove the access all downloads permission, does it work? Can you post your flutter doctor for that issue? I need more details of the device’s Android version and model.
> 
> Thank you.

@miguelpruivo Hi. it works without ACCESS_ALL_DOWNLOADS. I added it because supposed it will work normally. but this permission does not affect.
![photo_2019-08-22 11 28 41](https://user-images.githubusercontent.com/20066108/63499243-271d8b00-c4d0-11e9-8959-bf0aa90b3701.jpeg)

**Comment by miguelpruivo** [comment] 2019-08-22 08:42
Does that happen in a simulator too or only a real device?

**Comment by kleyos** [comment] 2019-08-24 10:50
> Does that happen in a simulator too or only a real device?

On the simulator the same. I noticed picker opens modal dialog twice. That's why I have to pick file two times

**Comment by miguelpruivo** [comment] 2019-08-29 17:38
Hi, I can't replicate the dialog opening twice, can you tell me the steps to reproduce this? It only seems to open once for me, as it should.

**Comment by kleyos** [comment] 2019-09-01 07:16
> Hi, I can't replicate the dialog opening twice, can you tell me the steps to reproduce this? It only seems to open once for me, as it should.

For example, I press a button to pick a file and don't pick it, just press the back button. I have to press two times because two dialogs are opened

**Comment by miguelpruivo** [comment] 2019-09-01 10:57
@kleyos yesterday `1.4.0` was released with some Android improvements, could you please give it a try and see if it has fixed that for you? Thank you.

**Comment by kleyos** [comment] 2019-09-01 13:31
> @kleyos yesterday `1.4.0` was released with some Android improvements, could you please give it a try and see if it has fixed that for you? Thank you.

HI. the same behavior. Just other messages
`I/FilePicker(17864): [SingleFilePick] File URI:content://com.android.providers.downloads.documents/document/4905
E/FilePickerUtils(17864): Getting for API 19 or abovecontent://com.android.providers.downloads.documents/document/4905
E/FilePickerUtils(17864): Document URI
E/FilePickerUtils(17864): Downloads External Document URI
D/DecorView(17864): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@773042b[MainActivity]
W/RenderThread(17864): type=1400 audit(0.0:2569813): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16621 scontext=u:r:untrusted_app:s0:c48,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    (17864): Access denied finding property "vendor.debug.egl.changepixelformat"
E/libc    (17864): Access denied finding property "vendor.debug.egl.changepixelformat"
W/1.gpu   (17864): type=1400 audit(0.0:2569814): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16621 scontext=u:r:untrusted_app:s0:c48,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
I/FilePickerUtils(17864): Caching file from remote/external URI
E/libc    (17864): Access denied finding property "vendor.debug.egl.swapinterval"
W/RenderThread(17864): type=1400 audit(0.0:2569815): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16621 scontext=u:r:untrusted_app:s0:c48,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    (17864): Access denied finding property "vendor.debug.egl.swapinterval"
W/1.gpu   (17864): type=1400 audit(0.0:2569816): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16621 scontext=u:r:untrusted_app:s0:c48,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
I/FilePickerUtils(17864): File loaded and cached at:/data/user/0/com.lits.switchin/cache/17.08.2019hcGmvokKaEC2dlkNb3K1Q.pdf
I/FilePicker(17864): Absolute file path:/data/user/0/com.lits.switchin/cache/17.08.2019hcGmvokKaEC2dlkNb3K1Q.pdf
I/FilePicker(17864): Checking permission: android.permission.READ_EXTERNAL_STORAGE
W/System  (17864): A resource failed to call close. 
I/chatty  (17864): uid=10304(com.lits.switchin) FinalizerDaemon identical 2 lines
W/System  (17864): A resource failed to call close. `

**Comment by kleyos** [comment] 2019-09-01 13:31
android.permission.READ_EXTERNAL_STORAGE  are granted

**Comment by miguelpruivo** [comment] 2019-09-01 15:15
Yes, if you hadn’t the permission, it would fail on picking the file at all. 

Anyway, could you please try with a different emulator? It might be on your implementation side as this seems to happen only with you, so far. Are you awaiting for the picker to pick the file or registering a callback?

**Comment by kleyos** [comment] 2019-09-01 15:39
As far as I got it is the problem of Android 9. for lower versions works correctly.

**Comment by kleyos** [comment] 2019-09-01 15:40
[how_it_works.zip](https://github.com/miguelpruivo/flutter_file_picker/files/3563660/how_it_works.zip)
here the video

**Comment by miguelpruivo** [comment] 2019-09-01 17:16
@kleyos thank you. That's odd. Could you try with the example app provided with the plugin? Because I can't really seem to be able to replicate that, it can be something related to the custom rom (Oxygen) used in the OPO phones.

**Comment by miguelpruivo** [comment] 2019-09-02 13:51
Any news on this @kleyos? 🙂

**Comment by miguelpruivo** [comment] 2019-09-22 10:39
I'm closing this since there's no further information from you @kleyos. Feel free to reopen if this is still an issue for you.

Thank you.

**Closed by miguelpruivo** 2019-09-22 10:39 UTC
Labels: awaiting response
