### ISSUE TITLE
calling await FilePicker.getFile() reset the textFormFields

### ISSUE THREAD

**Issue by jpainam** [miguelpruivo/flutter_file_picker#199] opened 2020-01-26 17:39 UTC
Hi, calling `await FilePicker.getFile()` on button pressed resets the previous textFormfield. I even tried to set the `initialValue` of textFormfield, but it didn't work. 
Any one facing the same issue here?
```dart

C:\Users\Paul>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter\flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

**Comment by miguelpruivo** [comment] 2020-01-26 18:09
@jpainam with your description this seem to have nothing related with the plugin itself. That’s because you have your `TextFormField` in a `StatelessWidget` and because returning from the picker may trigger a new frame, it can result in loosing the `TextFormField`s text. 

This should happen with any other widget/plugin that would schedule a new frame. As a solution, if your `TextFormField` isn’t in a `State` of a `StatefulWidget` convert it to one. You can also try using a custom `TextEditingController`.

Setting the `initialText` will only result the first time that widget is built not afterwards.

Closing since this has nothing to do with the package, but we can further continue the discussion if you still need help.

Thank you.

**Comment by jpainam** [comment] 2020-01-26 21:32
My `TextFormField` is inside a `StatefullWidget`. Replacing your pluging with any other plugin such as `image_picker` from the flutter team didn't reset my `textformfield`. That why i opened the issue here. If no one has experienced the same issue, then  We can close this issue. I

**Comment by miguelpruivo** [comment] 2020-01-26 22:31
@jpainam there must be something somewhere else then. 

This is the kind of issue that can’t be related at all with the plugin because it only gets you the path of the file(s) without scheduling any new frame. 

Does that happen on iOS, Android or both? Are you using a custom `TextEditingController`?

**Comment by jpainam** [comment] 2020-01-27 10:59
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1701705/73169443-07e9f000-4137-11ea-890e-871797a48040.gif)
No custom `TextEditingController`. I just tried with a fresh flutter app `The counter app`. Here a gif showing the result.
Here the code
```dart
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }
   File f ;

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(
              maxLines: 2,
            ),
            RaisedButton(
              child: Text("Load file"),
              onPressed: () async {
              var ff = await FilePicker.getFile();
                setState(() {
                  f = ff;
                });
              },
            ),
            Text(
              f == null ? "No file selected" : "${f.path}",
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by miguelpruivo** [comment] 2020-01-27 11:19
Thank you. Could you please answer to my previous questions? That'd help.

**Comment by jpainam** [comment] 2020-01-27 11:22
I just tried this on a real device Android. not on iOS
No custom `TextEditingController`

**Comment by miguelpruivo** [comment] 2020-01-27 11:24
Could you please try in an iOS emulator and/or other Android? 

Thank you.

**Comment by jpainam** [comment] 2020-01-27 11:43
I got the same results on an android emulator. sorry, I don't have an environment set up for iOS.

**Comment by jpainam** [comment] 2020-01-27 11:47
Check this gif. The behavior is different on an emulator. The content of the textfield remained for the first time. Second time, the content is cleared.
![untitled](https://user-images.githubusercontent.com/1701705/73172354-c4df4b00-413d-11ea-84f2-a191d5ebd747.gif)

**Comment by miguelpruivo** [comment] 2020-01-27 12:27
I’ll take a look and see if I can reproduce it. 

Thank you.

**Comment by miguelpruivo** [comment] 2020-02-21 11:48
Hi, I've tried to reproduce your issue and it indeed happens but so it does with [image_picker](https://pub.dev/packages/image_picker#-readme-tab-) as well.

Replacing this line:
```
 var ff = await FilePicker.getFile();
```
with
```
 var ff = await ImagePicker.pickImage(source: ImageSource.gallery);
```
results in the exact same issue, which is not actually an issue liked suspected in my [previous answer](https://github.com/miguelpruivo/flutter_file_picker/issues/199#issuecomment-578527694).

You need to provide a `TextEditingController` in order to keep changes when your `TextFormField` rebuilds with focus. Just like suggested in an [similar issue](https://github.com/flutter/flutter/issues/16391#issuecomment-400550953).

Closing as this behaves as expected.
Let me know if you still need any doubt with this.

Thank you!

**Closed by miguelpruivo** 2020-02-21 11:48 UTC
Labels: bug
