### ISSUE TITLE
App close after button pressed to open file picker.

### ISSUE THREAD

**Issue by L15V** [miguelpruivo/flutter_file_picker#698] opened 2021-04-25 15:05 UTC
When clicking the button to open the file explorer, the app close before even open the file explorer without any error messages.

**Platform**
- [] Web

**Platform OS version**
Ubuntu 20.04.2 LTS with google chrome

**How are you picking?**
```
`ElevatedButton(
                      onPressed: () async {
                        FilePickerResult result = await FilePicker.platform
                            .pickFiles(type: FileType.image);

                        if (result != null) {
                          setState(() {
                            _image = File(result.files.single.path);
                          });
                        } else {
                          // User canceled the picker
                        }
                      },
                      child: Row(children: [
                        Icon(Icons.add_a_photo),
                        Text(' Voeg foto toe'),
                      ]),
                    ),`
```

**Details to reproduce the issue**
- Create button to open file picker. (See code above)
- Click button.

**Error Log**
Application finished.
Exited (sigterm)

**Flutter Version details**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale nl_NL.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (1 available)

****Edit****
Just test it on Windows, and there it works, so seems like a problem on a linux machine.

**Comment by miguelpruivo** [comment] 2021-04-26 20:17
@L15V hi, unless you have a way to always replicate it or a stack trace, it will be hard to diagnose what might be happen. Could be an edge case related with your browser.

**Comment by L15V** [comment] 2021-04-28 19:10
@miguelpruivo 

To replicate the fault, run the code below on a ubuntu distro:

`
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
File _image;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(

        child: ElevatedButton(
                      onPressed: () async {
                        FilePickerResult result = await FilePicker.platform
                            .pickFiles(type: FileType.image);

                        if (result != null) {
                          setState(() {
                            _image = File(result.files.single.path);
                          });
                        } else {
                          // User canceled the picker
                        }
                      },
                      child: Row(children: [
                        Icon(Icons.add_a_photo),
                        Text(' Add file'),
                      ]),
                    ),
      ),
    );
  }
}
`

This is the init project of flutter changed with the button function that makes the app crashed on ubuntu. Tested it on Windows and there it works perfect.

**Comment by miguelpruivo** [comment] 2021-05-02 14:34
Hi, I don’t have any partition with Ubuntu as of now, if you manage to fix it, please issue a PR.

Thank you!

**Comment by EmanueleVinci** [comment] 2021-05-24 08:45
duplicate of #695

**Closed** 2021-05-25 11:23 UTC
Labels: bug, help wanted, web
