### ISSUE TITLE
How can I get extension on WEB?

### ISSUE THREAD

**Issue by michaldev** [miguelpruivo/flutter_file_picker#491] opened 2020-11-10 14:09 UTC
I try like this:
```
  var result = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['jpg', 'pdf'], allowMultiple: false);
  print(result.files.single.extension);
```

But this work only on mobile devices.

**Comment by miguelpruivo** [comment] 2020-11-10 14:47
@michaldev it should work on web as well. Which browser are you trying on?

**Comment by michaldev** [comment] 2020-11-10 14:57
Chrome. I got null.

**Comment by miguelpruivo** [comment] 2020-11-10 15:03
It shouldn't actually. Have you tried with a different one?

**Comment by sultanmyrza** [comment] 2020-11-11 09:23
have same issue path is null on flutter web
I created more detailed issue for others to follow 
https://github.com/miguelpruivo/flutter_file_picker/issues/495

**Comment by miguelpruivo** [comment] 2020-11-11 10:04
@sultanmyrza #495 is closed since it’s working as intended. You must use `bytes` property on the web since absolute paths aren’t supported by browsers.

**Comment by sultanmyrza** [comment] 2020-11-11 10:53
@miguelpruivo  I'm trying to do something like this but can't make it work on web
```
    FilePickerResult result = await FilePicker.platform.pickFiles();

    if (result != null) {
      var bytes = result.files.single.bytes;
      var fileName = result.files.single.name;

      // dart:html 
      var file = File(bytes, fileName);
      // dart: io
      var file = await File(fileName).writeAsBytes(bytes);

      // TODO: upload to firebase storage
      UploadTask task = uploadFile(file, fileName);
```

**Comment by miguelpruivo** [comment] 2020-11-16 11:37
Closing as this should be fixed on the latest version (2.0.13).

Feel free to reopen if you still experience any problem related to it.

Thank you!

**Closed by miguelpruivo** 2020-11-16 11:37 UTC
Labels: suggestion
